### PR TITLE
adding pyproject.toml

### PR DESCRIPTION
**Pull request by cvalaas**

### CODE REVIEW

**Comment by cvalaas** [comment]
This build is failing when travis tries to execute "python setup.py build" (which fails because I removed setup.py).
@mozafrank , should we just remove the travis stuff since we're moving away from travis(?).
Or should we fix that test command? And if so, do you know how?

**Comment by mozafrank** [comment]
@cvalaas my take is we should deprecate travis-ci and standardize on cloudbuild. 

I think in cases of "python setup.py build" the correct analog would be "poetry build" unless anyone disagrees.

**Comment by cvalaas** [comment]
`poetry build` would build the packages for distribution, but I don't think it would run any tests (which the .travis.yaml file seems to indicate is the point). shrug, maybe `python3 setup.py build` doesn't/didn't run any tests, either.

**Comment by mozafrank** [comment]
good point @cvalaas it doesn't appear tests were ever implemented into setup.py for cloudconfig anyhow. I think a command that might work for us would be `poetry run behave dpm/tests/bdd` run either in the Dockerfile or via cloudbuild.yaml

**Comment by cvalaas** [comment]
yeah, agree. or just install the libs thru docker and run the tests thru python; no poetry required.

**Comment by bsieber-mozilla** [comment]
Unsure how you all feel, but I think it's a candidate to wrap tox around as well.

**Comment by mozafrank** [comment]
@bsieber-mozilla I'm glad you called that out, as I was going through this it occurred to me "oh this is where tox would be nice" lol

**Comment by bsieber-mozilla** [comment]
I think in the cloud alert's PR I have the cloudbuild>docker> tox> poetry somewhat figured out.

Just scared of all the things that will fall upon merge. We can cherry pick and get those added in though (https://github.com/mozilla-it/cloudalerts/pull/6)

**Comment by cvalaas** [comment]
You/we can merge the existing PRs first if you want and I'll take care of any reconciling that has to happen between that and this one.
I just wanted to get this stuff in there so I could push it to the PyPI server

**Comment by bsieber-mozilla** [comment]
https://github.com/mozilla-it/cloudconfig/pull/32

**Pull request merged**
